#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular.Providers.Web.Views.App.Invoice
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Angular.Providers.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/App/Invoice/Invoice.cshtml")]
    public partial class Invoice : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Invoice()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div ng-switch");

WriteLiteral(" on=\"formStatus\"");

WriteLiteral(" ng-controller=\"InvoiceController\"");

WriteLiteral(">\r\n    \r\n    <div ng-cloak");

WriteLiteral(" class=\"server-side-message-container\"");

WriteLiteral(">        \r\n        <div");

WriteLiteral(" class=\"caution-alert message-caution-container\"");

WriteLiteral(" ng-show=\"messages.caution.length > 0\"");

WriteLiteral(" ng-repeat=\"m in messages.caution\"");

WriteLiteral(">           \r\n           <div");

WriteLiteral(" class=\"caution message-text\"");

WriteLiteral(">                \r\n                <p>{{m.text}}</p>                \r\n           " +
" </div>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"message-close-button\"");

WriteLiteral(" ng-click=\"RemoveMessage(messages.caution, m)\"");

WriteLiteral("></button>\r\n            </div>\r\n        <div");

WriteLiteral(" class=\"error-alert message-error-container\"");

WriteLiteral(" ng-show=\"messages.error.length > 0\"");

WriteLiteral(" ng-repeat=\"m in messages.error\"");

WriteLiteral(">            \r\n            <div");

WriteLiteral(" class=\"error message-text\"");

WriteLiteral(">                \r\n                <p>{{m.text}}</p>                \r\n           " +
" </div>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"message-close-button\"");

WriteLiteral(" ng-click=\"RemoveMessage(messages.error, m)\"");

WriteLiteral("></button>            \r\n        </div>\r\n        <div");

WriteLiteral(" class=\"success-alert message-success-container\"");

WriteLiteral(" ng-show=\"messages.success.length > 0\"");

WriteLiteral(" ng-repeat=\"m in messages.success\"");

WriteLiteral(">            \r\n            <div");

WriteLiteral(" class=\"success message-text\"");

WriteLiteral(">                \r\n                <p>{{m.text}}</p>                \r\n           " +
" </div>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"message-close-button\"");

WriteLiteral(" ng-click=\"RemoveMessage(messages.success, m)\"");

WriteLiteral("></button>            \r\n        </div>        \r\n    </div>\r\n          \r\n    <div " +
"ng-switch-default>\r\n        <h2>Invoice form.</h2>\r\n        <div>\r\n            <" +
"b>Invoice:</b>\r\n            \r\n            <div>\r\n                User name: <inp" +
"ut");

WriteLiteral(" type=\"text\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" ng-model=\"formData.userName\"");

WriteLiteral(" required>\r\n            </div>\r\n            <div>\r\n                Quantity: <inp" +
"ut");

WriteLiteral(" type=\"number\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" ng-model=\"formData.qty\"");

WriteLiteral(" required>\r\n            </div>\r\n            <div>\r\n                Costs: <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" ng-model=\"formData.cost\"");

WriteLiteral(" required>\r\n                <select");

WriteLiteral(" ng-model=\"formData.inCurr\"");

WriteLiteral(">\r\n                    <option");

WriteLiteral(" ng-repeat=\"c in currencies\"");

WriteLiteral(">{{c}}</option>\r\n                </select>\r\n            </div>\r\n            <div>" +
"\r\n                <b>Total:</b>\r\n                <span");

WriteLiteral(" ng-repeat=\"c in currencies\"");

WriteLiteral(">\r\n                    {{total(c) | currency:c}}\r\n                </span>\r\n      " +
"          <button");

WriteLiteral(" class=\"btn\"");

WriteLiteral(" ng-click=\"pay()\"");

WriteLiteral(">Pay</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" ng-switch-when=\"Submited\"");

WriteLiteral(">\r\n        <h1>Thank you!!</h1>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
